apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: demo
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      restartPolicy: Always
      containers:
      - name: flask-app
        image: flask-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: "0.5"
            memory: 512Mi

# kubectl run flask-app --image=flask-app --image-pull-policy=Never --port=5000  --generator=deployment/v1beta1
# kubectl expose rc flask-app --type=NodePort