apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: demo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: flask
  type: NodePort
